apiVersion: v1
kind: Service
metadata:
  name: kube-demo-worker-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: kube-demo-worker-app
  ports:
    - port: 80
      targetPort: 3001
      protocol: TCP