version: "3"

services:

  db:
    container_name: mariadb2
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  adminer:
    container_name: adminer2
    image: adminer
    restart: always
    ports:
      - 8081:8080