apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: balancer
  namespace: default
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: kube-demo-worker-svc
          servicePort: 80