apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-bar-app
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-bar-app
  template:
    metadata:
      labels:
        app: kube-bar-app
    spec:
      containers:
        - image: h0x91b/bar:v1
          name: nginx
          ports:
            - containerPort: 3002