apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-bar-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-bar-app
  template:
    metadata:
      labels:
        app: kube-bar-app
    spec:
      containers:
        - image: h0x91b/bar:v1
          name: kube-bar-app
          ports:
            - containerPort: 3002
              protocol: TCP